### ISSUE TITLE
This simulator does not exist or is not available

### ISSUE THREAD

**Issue by MontassirGhanmy** [eureka2/G6K#4]
Hi,
I did install the G6K simulator as described with wamp server but after I tried to run it I get the following
![capture](https://user-images.githubusercontent.com/26067730/40578221-54277d5e-6108-11e8-85cd-6ad1b21a5aec.JPG)

**Comment by eureka2** [comment]
Hello,

I need more information to help you:
- Have you installed the demo simulator?
- Which version of G6K did you install? 3.2.7 or dev?
- What is the php version?
- What rdbms do you use?

**Comment by MontassirGhanmy** [comment]
* Yes
* I'm not sure regarding the version. I simply followed the instructions on the repo homage page. I assumed it downloaded the latest version. 
* PHP 5.7
* MySQL , I see the table fos_user was created ( the only table that was created on the db )

**Comment by eureka2** [comment]
Normally you should see the 'marate' table in the demo database :
![image](https://user-images.githubusercontent.com/200478/40578899-d598fcb4-611c-11e8-8302-9888efc5ab7d.png)
Otherwise, maybe the user did not have the 'create database' privilege at the time of installation!

Connect to the administration module, go to "Data sources" and click the "Import data source" button :
 ![image](https://user-images.githubusercontent.com/200478/40578994-a0cce62e-611e-11e8-8c24-1b69791fae2d.png)
Select "demo.schema.json and demo.json in the "src\EUREKA\G6KBundle\Resources\data\databases"

**Comment by eureka2** [comment]
@MontassirGhanmy

Is the problem solved?
I will close this issue if I do not have an answer within 8 days
